Use "channel" as the "message_thread_id" when using the Telegram template
Unpackerr/unpackerr pull request #314
Opened 2023-06-15 02:51 UTC by yegle

See reference in https://core.telegram.org/bots/api#sendmessage

2023-06-15 17:19 UTC, davidnewhall requested changes
Can you tell us what this does? What problem it solves? Why someone would want to provide the new field to telegram?

2023-06-15 17:19 UTC, davidnewhall commented on pkg/unpackerr/webhooks_templates.go
> +  {{- if channel }}"message_thread_id": {{channel}}{{end -}},
The comma at the end should probably be inside the if/end blocks.

2023-07-24 19:47 UTC, yegle commented
This was a new feature from telegram, where you can specify a `message_thread_id` and it will become part of a named topic in the chat room.

I guess maybe it would be easier to override `webhook.template_path` and add the `messate_thread_id`.

2023-07-24 19:47 UTC, closed without merging

2023-07-29 08:28 UTC, davidnewhall commented
I don't mind adding it. Just wanted to know more about it since I don't send telegram notifications myself. I also wanted to make sure that comma wasn't out of place. You're welcome to re-open this and fix the comma. Thank you!